Repository CheckmarxDev/ast-cli-java-wrapper, pull requests merged in 2025-02, with the labels that each got.

#399 Add GetStates command and update with custom state functionality (AST-81676)
  src/main/java/com/checkmarx/ast/predicate/CustomState.java
  src/main/java/com/checkmarx/ast/predicate/Predicate.java
  src/main/java/com/checkmarx/ast/wrapper/CxConstants.java
  src/main/java/com/checkmarx/ast/wrapper/CxWrapper.java
  src/main/java/com/checkmarx/ast/wrapper/Execution.java
  src/test/java/com/checkmarx/ast/PredicateTest.java
Labels: feature

#398 Update checkmarx-ast-cli binaries with 2.3.13
  checkmarx-ast-cli.version
  src/main/resources/cx-linux
  src/main/resources/cx-linux-arm
  src/main/resources/cx-mac
  src/main/resources/cx.exe
Labels: feature, cxone

#402 Refactor execution result handling in Execution.java
  src/main/java/com/checkmarx/ast/wrapper/Execution.java
  src/test/java/com/checkmarx/ast/ScanTest.java
Labels: bug

#403 Update triageGetStates method to return CustomState and remove test ignore
  src/main/java/com/checkmarx/ast/wrapper/CxWrapper.java
  src/test/java/com/checkmarx/ast/PredicateTest.java
Labels: bug

#404 Refactor field access in Execution and Predicate classes to use getFields() (AST-83201)
  src/main/java/com/checkmarx/ast/predicate/Predicate.java
  src/main/java/com/checkmarx/ast/wrapper/Execution.java
Labels: bug
